language: go

go:
  - 1.11.5

install:
  - go get -u github.com/go-bindata/go-bindata/...
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u github.com/goreleaser/goreleaser

before_script:
  - dep ensure
  - go generate

script:
  - go vet ./...
  - go test ./...

before_deploy:
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
